//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> Statement1()
 * f1 -> Statement3()
 * f2 -> Statement2()
 * f3 -> ";"
 */
public class Statementt implements Node {
   public Statement1 f0;
   public Statement3 f1;
   public Statement2 f2;
   public NodeToken f3;

   public Statementt(Statement1 n0, Statement3 n1, Statement2 n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Statementt(Statement1 n0, Statement3 n1, Statement2 n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = new NodeToken(";");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

